language: node_js
node_js:
  - "8"
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - npm install -g yarn
install:
  - yarn
script:
  - yarn test
deploy:
  - provider: script
    script: yarn deploy
    skip_cleanup: true
    on:
      branch: master
